### ISSUE TITLE
Instructions on how to add as a theme in wordpress

### ISSUE THREAD

**Issue by missedabit** [dxw/govuk-theme#86]
Hi, is there any instructions ( or a working example ) on how to add this theme to wordpress please, once I have downloaded the zip file. I am new to Wordpress so would appreciate a "step-by-step" guide so i can view the look and feel - would be really useful for me.  Thanks in advance.

**Comment by snim2** [comment]
Hi @missedabit sorry we missed your issue, probably you have fixed this by now. 

We generally don't include instructions like this because how you install a theme might depend on whether you are using a managed hosting platform (like wordpress.com) to host your site, or whether you are managing your site by hand. 

Either way, [this documentation from wordpress.org](https://wordpress.org/documentation/article/worik-with-themes/) might be helpful to you.
